name: tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        make install
    - name: run tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: make test
    - name: test & publish code coverage
      uses: paambaati/codeclimate-action@v2.7.4
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: make test-coverage
        debug: true